# Generated by Django 5.2 on 2025-09-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_apellidos",
                    models.CharField(max_length=200, verbose_name="Nombre y apellidos"),
                ),
                (
                    "asunto",
                    models.CharField(
                        choices=[
                            ("informacion_general", "Información general"),
                            ("extraescolares", "Extraescolares"),
                            ("aula_matinal", "Aula matinal"),
                            ("actividades_eventos", "Actividades y eventos"),
                            ("apoyo_educativo", "Apoyo educativo"),
                            ("participacion_familiar", "Participación familiar"),
                            ("sugerencias", "Sugerencias"),
                            ("quejas", "Quejas o reclamaciones"),
                            ("otros", "Otros"),
                        ],
                        max_length=50,
                        verbose_name="Asunto relacionado",
                    ),
                ),
                ("mensaje", models.TextField(verbose_name="Mensaje")),
                (
                    "email_contacto",
                    models.EmailField(
                        blank=True,
                        help_text="Opcional: para poder responderte",
                        max_length=254,
                        null=True,
                        verbose_name="Email de contacto",
                    ),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de envío"
                    ),
                ),
                (
                    "respondido",
                    models.BooleanField(default=False, verbose_name="Respondido"),
                ),
                (
                    "notas_internas",
                    models.TextField(
                        blank=True,
                        help_text="Para uso interno de la Apyma",
                        verbose_name="Notas internas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de contacto",
                "verbose_name_plural": "Mensajes de contacto",
                "ordering": ["-fecha_envio"],
            },
        ),
    ]
