# Generated by Django 5.2.5 on 2025-09-28 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Socio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_socio",
                    models.CharField(
                        help_text="Número único de identificación del socio",
                        max_length=10,
                        unique=True,
                        verbose_name="Número de socio",
                    ),
                ),
                (
                    "fecha_alta",
                    models.DateField(auto_now_add=True, verbose_name="Fecha de alta"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        help_text="Teléfono de contacto del socio",
                        max_length=15,
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el socio está actualmente activo",
                        verbose_name="Socio activo",
                    ),
                ),
                (
                    "direccion",
                    models.TextField(
                        blank=True,
                        help_text="Dirección del domicilio del socio",
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "dni",
                    models.CharField(
                        blank=True,
                        help_text="Documento Nacional de Identidad o NIE",
                        max_length=9,
                        verbose_name="DNI/NIE",
                    ),
                ),
                (
                    "nombre_padre",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre del padre"
                    ),
                ),
                (
                    "nombre_madre",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre de la madre"
                    ),
                ),
                (
                    "correo_contacto_1",
                    models.EmailField(
                        blank=True,
                        help_text="Email principal de contacto",
                        max_length=254,
                        verbose_name="Correo de contacto 1",
                    ),
                ),
                (
                    "correo_contacto_2",
                    models.EmailField(
                        blank=True,
                        help_text="Email secundario de contacto",
                        max_length=254,
                        verbose_name="Correo de contacto 2",
                    ),
                ),
                (
                    "nombre_alumnos",
                    models.TextField(
                        blank=True,
                        help_text="Nombres de los hijos/alumnos (uno por línea)",
                        verbose_name="Nombre de los alumnos",
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True,
                        help_text="Número de cuenta bancaria (IBAN)",
                        max_length=34,
                        verbose_name="IBAN",
                    ),
                ),
                (
                    "bic",
                    models.CharField(
                        blank=True,
                        help_text="Código BIC/SWIFT del banco",
                        max_length=11,
                        verbose_name="BIC/SWIFT",
                    ),
                ),
                (
                    "modelo_estudios",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("modelo_d", "Modelo D"),
                            ("pai", "PAI (Programa de Aprendizaje en Inglés)"),
                        ],
                        help_text="Modelo educativo del centro",
                        max_length=20,
                        verbose_name="Modelo de estudios",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Socio",
                "verbose_name_plural": "Socios",
                "ordering": ["numero_socio"],
            },
        ),
    ]
