# Generated by Django 5.2.5 on 2025-09-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_socio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socio",
            name="telefono",
        ),
        migrations.AddField(
            model_name="socio",
            name="apellidos_familia",
            field=models.CharField(
                blank=True,
                help_text="Apellidos familiares",
                max_length=200,
                verbose_name="Apellidos de la familia",
            ),
        ),
        migrations.AddField(
            model_name="socio",
            name="numero_hijos",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Cantidad total de hijos",
                null=True,
                verbose_name="Número de hijos",
            ),
        ),
        migrations.AddField(
            model_name="socio",
            name="poblacion",
            field=models.CharField(
                blank=True,
                help_text="Ciudad o pueblo de residencia",
                max_length=100,
                verbose_name="Población",
            ),
        ),
        migrations.AddField(
            model_name="socio",
            name="telefono_1",
            field=models.CharField(
                blank=True,
                help_text="Teléfono principal de contacto",
                max_length=15,
                verbose_name="Teléfono 1",
            ),
        ),
        migrations.AddField(
            model_name="socio",
            name="telefono_2",
            field=models.CharField(
                blank=True,
                help_text="Teléfono secundario de contacto",
                max_length=15,
                verbose_name="Teléfono 2",
            ),
        ),
    ]
