# Generated by Django 5.2.5 on 2025-09-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0003_remove_socio_telefono_socio_apellidos_familia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        help_text="Fecha en la que se realizará la actividad",
                        verbose_name="Fecha",
                    ),
                ),
                (
                    "hora_comienzo",
                    models.TimeField(
                        help_text="Hora de inicio de la actividad",
                        verbose_name="Hora de comienzo",
                    ),
                ),
                (
                    "hora_finalizacion",
                    models.TimeField(
                        blank=True,
                        help_text="Hora de finalización de la actividad (opcional)",
                        null=True,
                        verbose_name="Hora de finalización",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción detallada de la actividad",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen representativa de la actividad",
                        null=True,
                        upload_to="actividades/imagenes/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Enlace web relacionado con la actividad (opcional)",
                        verbose_name="Enlace",
                    ),
                ),
                (
                    "tipo_actividad",
                    models.CharField(
                        choices=[
                            ("taller", "Taller"),
                            ("excursion", "Excursión"),
                            ("reunion", "Reunión"),
                            ("festival", "Festival"),
                            ("evento_social", "Evento social"),
                        ],
                        help_text="Categoría de la actividad",
                        max_length=20,
                        verbose_name="Tipo de actividad",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si la actividad está visible y activa",
                        verbose_name="Actividad activa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
                "ordering": ["fecha", "hora_comienzo"],
            },
        ),
    ]
