# Generated by Django 5.2.5 on 2025-09-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0004_actividad"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividad",
            name="donde",
            field=models.CharField(
                blank=True,
                help_text="Lugar donde se realizará la actividad",
                max_length=200,
                verbose_name="Dónde",
            ),
        ),
    ]
