# Generated by Django 5.2 on 2025-10-08 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0005_actividad_donde"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "titulo_eu",
                    models.CharField(
                        blank=True,
                        help_text="Opcional: título en euskera",
                        max_length=200,
                        verbose_name="Título (Euskera)",
                    ),
                ),
                (
                    "resumen",
                    models.TextField(
                        help_text="Breve descripción que aparecerá en la lista de noticias",
                        max_length=300,
                        verbose_name="Resumen",
                    ),
                ),
                (
                    "resumen_eu",
                    models.TextField(
                        blank=True,
                        help_text="Opcional: resumen en euskera",
                        max_length=300,
                        verbose_name="Resumen (Euskera)",
                    ),
                ),
                ("contenido", models.TextField(verbose_name="Contenido completo")),
                (
                    "contenido_eu",
                    models.TextField(
                        blank=True,
                        help_text="Opcional: contenido completo en euskera",
                        verbose_name="Contenido completo (Euskera)",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen opcional para la noticia",
                        null=True,
                        upload_to="noticias/",
                        verbose_name="Imagen destacada",
                    ),
                ),
                (
                    "fecha_publicacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de publicación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificación"
                    ),
                ),
                (
                    "publicada",
                    models.BooleanField(
                        default=True,
                        help_text="Si está marcado, la noticia será visible para todos",
                        verbose_name="Publicada",
                    ),
                ),
                (
                    "destacada",
                    models.BooleanField(
                        default=False,
                        help_text="Las noticias destacadas aparecen primero",
                        verbose_name="Noticia destacada",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Se genera automáticamente del título",
                        max_length=200,
                        unique=True,
                        verbose_name="URL amigable",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        help_text="Usuario que creó la noticia",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Noticia",
                "verbose_name_plural": "Noticias",
                "ordering": ["-destacada", "-fecha_publicacion"],
            },
        ),
    ]
