# Generated by Django 5.2 on 2025-10-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0006_noticia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticia",
            name="contenido_eu",
            field=models.TextField(
                help_text="Contenido completo en euskera",
                verbose_name="Contenido completo (Euskera)",
            ),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="resumen_eu",
            field=models.TextField(
                help_text="Resumen en euskera",
                max_length=300,
                verbose_name="Resumen (Euskera)",
            ),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="titulo_eu",
            field=models.CharField(
                help_text="Título en euskera",
                max_length=200,
                verbose_name="Título (Euskera)",
            ),
        ),
    ]
