# Generated by Django 5.2 on 2025-10-08 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "usuarios",
            "0007_alter_noticia_contenido_eu_alter_noticia_resumen_eu_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noticia",
            name="autor",
        ),
        migrations.AddField(
            model_name="noticia",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha de creación",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="noticia",
            name="fecha_publicacion",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Fecha en que se publicará la noticia",
                verbose_name="Fecha de publicación",
            ),
        ),
    ]
