# Generated by Django 5.2 on 2025-10-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0008_remove_noticia_autor_noticia_fecha_creacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividad",
            name="titulo",
            field=models.CharField(
                blank=True,
                help_text="Título de la actividad",
                max_length=200,
                null=True,
                verbose_name="Título",
            ),
        ),
    ]
