# Generated by Django 5.2.5 on 2025-12-13 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_actividad_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcursoDibujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_nino', models.CharField(max_length=200, verbose_name='Nombre del niño')),
                ('curso', models.CharField(max_length=50, verbose_name='Curso')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('imagen', models.ImageField(upload_to='concurso_navidad/', verbose_name='Fotografía del dibujo')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('revisado', models.BooleanField(default=False, verbose_name='Revisado por comité')),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.socio', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Participación concurso',
                'verbose_name_plural': 'Participaciones concurso',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
