# Generated by Django 5.2.5 on 2025-12-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_concursodibujo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concursodibujo',
            name='curso',
            field=models.CharField(choices=[('3_anos', '3 años'), ('4_anos', '4 años'), ('5_anos', '5 años'), ('1_primaria', '1º Primaria'), ('2_primaria', '2º Primaria'), ('3_primaria', '3º Primaria'), ('4_primaria', '4º Primaria'), ('5_primaria', '5º Primaria'), ('6_primaria', '6º Primaria')], max_length=50, verbose_name='Curso'),
        ),
    ]
