# Generated by Django 5.2.5 on 2025-12-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_concursodibujo_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='concursodibujo',
            name='aceptado',
            field=models.BooleanField(default=False, verbose_name='Dibujo aceptado'),
        ),
    ]
