# Generated by Django 5.2.5 on 2025-12-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_concursodibujo_aceptado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concursodibujo',
            name='revisado',
        ),
    ]
