# Generated by Django 5.2.5 on 2025-12-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_remove_concursodibujo_revisado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsejoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del consejo educativo', max_length=200, verbose_name='Título')),
                ('titulo_eu', models.CharField(blank=True, help_text='Título en euskera', max_length=200, null=True, verbose_name='Título (Euskera)')),
                ('descripcion', models.TextField(help_text='Breve descripción que aparece en la tarjeta', verbose_name='Descripción corta')),
                ('descripcion_eu', models.TextField(blank=True, help_text='Descripción en euskera', null=True, verbose_name='Descripción corta (Euskera)')),
                ('slug', models.SlugField(help_text='Se genera automáticamente del título', max_length=200, unique=True, verbose_name='URL amigable')),
                ('archivo_html', models.CharField(help_text='Ruta relativa desde media/consejos/, ej: habitos-estudio.html', max_length=500, verbose_name='Ruta del archivo HTML')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen que aparece en la tarjeta', null=True, upload_to='consejos/', verbose_name='Imagen de portada')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, help_text='Solo los consejos activos son visibles', verbose_name='Activo')),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición (menor número aparece primero)', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Consejo Educativo',
                'verbose_name_plural': 'Consejos Educativos',
                'ordering': ['orden', '-fecha_publicacion'],
            },
        ),
    ]
