# Generated by Django 5.2.5 on 2025-12-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_consejoeducativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consejoeducativo',
            name='imagen_eu',
            field=models.ImageField(blank=True, help_text='Imagen en euskera que aparece en la tarjeta', null=True, upload_to='consejos/', verbose_name='Imagen de portada (Euskera)'),
        ),
    ]
