# Generated by Django 5.2.5 on 2026-01-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_consejoeducativo_imagen_eu'),
    ]

    operations = [
        migrations.AddField(
            model_name='concursodibujo',
            name='ganador',
            field=models.BooleanField(default=False, verbose_name='Dibujo ganador'),
        ),
    ]
